name: Download MP3 File

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download MP3 file
      run: |
        curl -L -o audio.mp3 "https://rr1---sn-i0ujipnvoa3-jhce.googlevideo.com/videoplayback?expire=1707570471&ei=xyDHZfmvF5imxN8P6I6mkAQ&ip=172.233.248.119&id=o-AABQjzRun4AtNtQ7nbhPJ5RKma9aeVxTtgLA6Fo63uWY&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=1398275065&dur=86399.171&lmt=1703248653606278&keepalive=yes&fexp=24007246&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgZW1bagVjGinHozZGEptwJVLRzVenFTCVBxA_OEgig6YCIQDpuClds1kK7G8aUaNMmiLo5SIMR1ZcbPMAjbJL08ikVA%3D%3D&title=24+Hours+of+Relaxing+Sleep+Music+%E2%80%A2+Deep+Sleep+Music%2C+Meditation%2C+Night+Sounds%2C+Relaxing+Music%2C+Calm&redirect_counter=1&rm=sn-aigesl7e&req_id=8ef307cd142ea3ee&cms_redirect=yes&cmsv=e&ipbypass=yes&mh=BJ&mip=103.21.165.213&mm=31&mn=sn-i0ujipnvoa3-jhce&ms=au&mt=1707548706&mv=m&mvi=1&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AAO5W4owRAIgWw-8W0y6mGN5zMzCWJUPmzYBMW7NlekRxk6mWj3F7nECIDYPmepw3DzSE-D7dvh4aHiLarjcKQVvy_oOt0XzWNg6"
    
    - name: Add MP3 file to repository
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'youremail@example.com'
        git add audio.mp3
        git commit -m "Add audio.mp3"
        git push
